"""Auth domain constants and helpers."""

ROLE_ADMIN = "admin"
ROLE_USER = "user"

INVITE_PENDING = "pending"
INVITE_ACCEPTED = "accepted"
INVITE_REVOKED = "revoked"

USER_STATUS_ACTIVE = "active"
USER_STATUS_BLOCKED = "blocked"
USER_STATUS_DISABLED = "disabled"

ACTIVE_USER_STATUSES = {USER_STATUS_ACTIVE}
INACTIVE_USER_STATUSES = {USER_STATUS_BLOCKED, USER_STATUS_DISABLED}
